
plugins {
    id 'com.android.application'
    
}

android {
    namespace 'com.test.cpp'
    compileSdk 33
    
    ndkVersion "24.0.8215888"
    buildToolsVersion "33.0.3"

externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.23.1"
        }
            }

    defaultConfig {
        applicationId "com.test.cpp"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
        
        externalNativeBuild {
			cmake {
                arguments '-DANDROID_ARM_NEON=TRUE',
				'-DANDROID_TOOLCHAIN=clang'
            }
        }
		
		ndk {
            abiFilters  'armeabi-v7a','arm64-v8a'
        }
        
        vectorDrawables { 
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
        
    }
    
}

dependencies {


    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    implementation("com.google.android.material:material:1.9.0")
}
